試用版
i3thuan5/weasel pull request #10
Opened 2020-04-29 02:00 UTC by niauah

2020-04-29 06:29 UTC, sih4sing5hong5 commented
@niauah 重發PR，改 draft

2020-04-29 06:29 UTC, sih4sing5hong5 requested changes
close PR，發新PR(改draft)

2020-05-04 02:03 UTC, a8568730 approved these changes
:100:

2020-07-06 06:08 UTC, niauah commented
改去用 https://github.com/i3thuan5/librime/pull/13

2020-07-06 06:08 UTC, closed without merging